#######################################################################################################
# CONFIGURACI�N DEL SERVIDOR
#######################################################################################################
#server.port=8081

#######################################################################################################
# CONEXI�N A BASE DE DATOS SQL SERVER: COLPENSIONES
#######################################################################################################

#spring.datasource.url=jdbc:sqlserver://192.168.1.68:1433;DatabaseName=ColpensionesBusinessCoreINT
#spring.datasource.username=soacol
#spring.datasource.password=S041nt25%
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Itegracion 

spring.datasource.url=jdbc:sqlserver://10.130.73.175:1435;DatabaseName=GD_NEGOCIO_AREAS
spring.datasource.username=intgdnegareas
spring.datasource.password=Soporte21
#local  spring 6
#spring.datasource.url=jdbc:sqlserver://localhost:1433;database=GD_NEGOCIO_AREAS
#spring.datasource.username=sa
#spring.datasource.password=Docker123!
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#QA

#spring.datasource.url=jdbc:sqlserver://10.120.73.175:1435;DatabaseName=GD_NEGOCIO_AREAS
#spring.datasource.username=qagdnegareas
#spring.datasource.password=Soporte21
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

filenet.puri=http://pvwqfn01.appqa.loc:9080/wsi/FNCEWS40MTOM/
filenet.username=GCDeclarAutom
filenet.password=o5qxC@72pJ
filenet.stanza=FileNetP8WSI


#######################################################################################################
# JPA / HIBERNATE
#######################################################################################################
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#######################################################################################################
# LOGGING
#######################################################################################################
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework=WARN
logging.config=classpath:log4j.xml








