
#spring.datasource.url=jdbc:postgresql://dpg-d7nujjflk1mc73d900c0-a.ohio-postgres.render.com:5432/smart_home_db_gq8s?sslmode=require
#spring.datasource.username=smart_home_db_gq8s_user
#spring.datasource.password=Q2QOlbAKQPmHef2Izr9YXNHUedjb1zSp
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#
#
#filenet.puri=http://pvwqfn01.appqa.loc:9080/wsi/FNCEWS40MTOM/
#filenet.username=GCDeclarAutom
#filenet.password=o5qxC@72pJ
#filenet.stanza=FileNetP8WSI
## ---------------------------------------------------------
## CONFIGURACIÓN DE JPA / HIBERNATE PARA POSTGRES
## ---------------------------------------------------------
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
########################################################################################################
## LOGGING
########################################################################################################
#logging.level.org.hibernate.SQL=debug
#logging.level.org.springframework=WARN
#logging.config=classpath:log4j.xml





#######################################################################################################
# produccion
#######################################################################################################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=${PORT:8080}

logging.level.org.hibernate.SQL=debug
logging.level.org.springframework=WARN
logging.config=classpath:log4j.xml

