[build]
  # Entra a la carpeta del proyecto
  base = "Frontend/smart-home-frontend"

  # Agregamos "--prerender false" para que no se quede trabado
  command = "ng build --prerender false"

  # IMPORTANTE: En Angular 17+, la carpeta de salida SIEMPRE es /browser
  publish = "dist/smart-home-frontend/browser"

[[redirects]]
  # Esto es para que no te dé 404 al recargar la página
  from = "/*"
  to = "/index.html"
  status = 200