[build]
  # Como el archivo ya está en la subcarpeta, el comando se ejecuta ahí mismo
  command = "ng build"
  
  # La ruta de publicación debe ser RELATIVA a donde está este archivo
  publish = "dist/smart-home-frontend/browser"

[[redirects]]
  # Esto es VITAL para que Angular funcione al refrescar la página
  from = "/*"
  to = "/index.html"
  status = 200