[build]
  # El comando para compilar
  command = "ng build"
  
  # La carpeta donde Angular REALMENTE guardó los archivos según el log
  publish = "dist/smart-home-frontend"

[[redirects]]
  # Esto evita el error 404 al recargar la página
  from = "/*"
  to = "/index.html"
  status = 200